### ISSUE TITLE
Not showing after deployment

### ISSUE THREAD

**Issue by asmraihan** [madox2/react-tagcloud#36]
tagcloud doesnt appear after being deployed to netlify and vercel. can anyone help me with that?

**Comment by madox2** [comment]
Hi, can provide more details, like if it works in a development mode, what kind of bundler do you use, can you see any errors in the console log?

**Comment by asmraihan** [comment]
yes its working perfectly on developer mode,and im using vite
i have attached ss from pre build in the readme of this repo
asmraihan/portfolio_frontendv3
(github.com) <https://github.com/asmraihan/portfolio_frontendv3>
live link here https://portfolio-frontendv3.vercel.app/
thanks again for looking into this

**Comment by madox2** [comment]
I see, in this file you are trying to display tags:
https://github.com/asmraihan/portfolio_frontendv3/blob/main/src/components/TextSphere.jsx

However the library you are using is not this one - `react-tagcoud`, but rather `TagCloud`.

Anyway, for what it is worth, maybe you could try using `useLayoutEffect` instead of `useEffect`. That would initialize the cloud after all DOM is mounted

**Comment by asmraihan** [comment]
Bro sorry for the late reply. finally fixed the issue. turns out I was
using the wrong package after all!!
 i was trying to use normal tagcloud where it wouldn't render in a react
project. they had a separate package for react.that seems to resolve the
issue.
Anyway thank you for your thoughtful reply. Even Though you didn't have to
help me im glad you found time to reply to my stupid message (being a
newbie) 😅🖤

**Comment by asmraihan** [comment]
> 

frank-mayer/react-tag-cloud use this package

**Comment by asmraihan** [comment]
@Sushmitha041 use this package 'frank-mayer/react-tag-cloud'
